---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: IMAGE
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: IMAGE
  labels:
    app: IMAGE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: IMAGE
  template:
    metadata:
      labels:
        app: IMAGE
    spec:
      containers:
        - name: IMAGE
          image: IMAGE_NAME