name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: gke-shared-des
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: hello-world-app
  CLUSTER_NAME: gke-shared-des
  REPOSITORY: super-duper
  IMAGE: nginx:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: install gke-cloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: build and push the docker image
        run: |
          gcloud auth configure-docker ${{ env.GKE_ZONE }}-docker.pkg.dev --quiet
          docker build -t ${{ env.GKE_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }} .
          docker push ${{ env.GKE_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}

      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          IMAGE: nginx
          IMAGE_NAME: ${{ env.GKE_ZONE }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.GKE_ZONE }}
          sed -i "s|GOOGLE_PROJECT|$GOOGLE_PROJECT|g" resources.yaml
          sed -i "s|IMAGE|$IMAGE|g" resources.yaml
          sed -i "s|IMAGE_NAME|$IMAGE_NAME|g" resources.yaml
          kubectl apply -f resources.yaml
