name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  PROJECT_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GKE_CLUSTER: gke-shared-des
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: hello-world-app
  REPOSITORY: super-duper
  IMAGE: nginx:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.PROJECT_SA_KEY }}
          export_default_credentials: true

      - name: build and push the docker image
        run: |
          gcloud auth configure-docker ${{ env.GKE_ZONE }}-docker.pkg.dev
          docker build -t ${{ env.GKE_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }} .
          docker push ${{ env.GKE_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}
